### ISSUE TITLE
The "HHexLayout" class will cause fatal error in Processing JavaScript Mode

### ISSUE THREAD

**Issue by Houdou** [hype/HYPE_Processing#117]
In HHexLayout class, there are some direction function which use "in" as argument.
This is fine for Java.
However, as  "in" is a keyword for JavaScript, when the ProcessingJS interpreter the code, it will fail.
I suggest to change the arguments to some other names that will not cause this problem.

**Comment by christophertino** [comment]
@Houdou we decided to drop support for Processing.js when we migrated to the Processing library format.  Checkout the 'pde_staging' branch if you want to still use processing.js.
