### ISSUE TITLE
Error while importing HYPE.jar lib in a processing sketch

### ISSUE THREAD

**Issue by jumahe** [hype/HYPE_Processing#122]
I'm getting this error: 
_Ignoring /Volumes/Data/Users/ju/Documents/Processing/libraries/HYPE/library/HYPE.jar (error in opening zip file)_
--> Any idea?
(Processing version: 3)

**Comment by hype** [comment]
and just to be sure on the steps...

1. https://github.com/hype/HYPE_Processing click "clone or download"
2. from dropdown click "Download ZIP"
3. unzip zip
4. navigate to "distribution" folder
5. unzip HYPE.zip
6. move unzipped folder "HYPE" to "/Documents/Processing/libraries/"

**Comment by jumahe** [comment]
Works perfectly now.
Sorry, I directly downloaded the .jar and .zip from the repo.
Thank you for your response and for your time.
Bests.
