### ISSUE TITLE
staging-lib

### ISSUE THREAD

**Issue by guykes** [hype/HYPE_Processing#135]
Hi there, this might be a dumb question, but how do i use the staging-lib besides (or instead of) the regular HYPE lib for testing new stuff? I've tried copying the contents of the staging lib in the regular HYPE lib, but then my .pde couldn't find the hype classes.

Any thoughts on this one?

Thanks!
G.

**Comment by hype** [comment]
no problem.

1. delete the HYPE folder in your "Processing/libraries" folder
2. download the https://github.com/hype/HYPE_Processing/tree/lib_staging .zip file
3. navigate to "distribution"
4. unzip HYPE.zip
5. move new HYPE folder to "Processing/libraries" folder

all good to go.

hope this helps,
