### ISSUE TITLE
Installing HYPE: The package “hype” does not exist. 

### ISSUE THREAD

**Issue by Evanto** [hype/HYPE_Processing#148]
Hi, I'm failing to install HYPE, please help. 
I downloaded from https://github.com/hype/HYPE_Processing/tree/lib_staging, unzipped into home/user/sketchbook/libraries (like in the Preferences window), renamed it to HYPE (similar to .jar file's name), restarted the IDE and tried to run examples, but got the message: 

> The package “hype” does not exist. You might be missing a library. 

Processing 3.3.7, Sublime 3, Ubuntu 16.04.4 LTS.

How do I make HYPE work?
Thank you!

**Comment by tracerstar** [comment]
Hi there.

Our code in github is actually a collection of the source code, examples, ant build files and a separate zip containing the compiled library.

To install HYPE, take a look in the unzipped folder you downloaded, and go to the "distribution" folder within it. There's a zip in there called HYPE.zip. Unzip that file into your Processing library and you should be all set to run the examples.

For reference, the file I'm talking about it:
https://github.com/hype/HYPE_Processing/blob/lib_staging/distribution/HYPE.zip
