### ISSUE TITLE
Cannot find class `HRotate`

### ISSUE THREAD

**Issue by wanbinkimoon** [hype/HYPE_Processing#149]
I think this is lack of documentation, and I have saw the TODO. 

BTW, I'm getting this error
```
build.pde:10:0:10:0: Cannot find a class or type named HRotate
```

I watched at the examples and the way I'm using the class is the same.
```
d
  .size(125)
  .loc(0,0)
  .anchorAt(H.CENTER)
  .noFill()
  .stroke(#FF7700);

HRotate r = new HRotate();
r.target(d).speedRad( TWO_PI/90 );
```

Then I looked into the source code and I couldn't found the class ... any help?

**Comment by tracerstar** [comment]
Did you download the library from the master branch or from the lib_staging branch? lib_staging is the most up to date and has HRotate in it.

https://github.com/hype/HYPE_Processing/tree/lib_staging
