### ISSUE TITLE
Remove "extra" border from elements inside HCanvas

### ISSUE THREAD

**Issue by danieltorrer** [hype/HYPE_Processing#163]
I'm getting an extra border in all the elements added to an HCanvas. My guess is that it's coming from the PGraphics transparency and it only occurs when using P3D. 
I added a sample code to test it.  

How can I remove them?

```
import hype.*;

PFont font1;
HCanvas canvas;

void setup() {
  size(640,640, P3D);
  H.init(this).background(#ffffff);
  
  canvas = (HCanvas) H.add(new HCanvas(P3D).autoClear(true));  


  font1 = createFont("Arial", 48);
  
  HText f1 = new HText("some regular text",48, font1);
  f1.fill(#98FCFF).anchorAt(H.CENTER).loc(width/2,height/2);
  f1.noStroke();
  canvas.add(f1);  // change this for H.add to see the difference

  H.drawStage();
  noLoop();
}

void draw() {}

```

**Comment by DonoG** [comment]
Depending on what you are doing, you might be able to get away with either

a) Not specifying P3D in your HCanvas:

`canvas = (HCanvas) H.add(new HCanvas().autoClear(true));  `

b) Changing the autoclear setting:

`canvas = (HCanvas) H.add(new HCanvas(P3D).autoClear(false));`

(Tested with processing 3.3.6 on Windows...your results may vary)

**Comment by hype** [comment]
close... need to add the autoClear(true) to H and remove it from HCanvas

```import hype.*;

PFont font1;
HCanvas canvas;

void setup() {
  size(640,640, P3D);
  H.init(this).background(#ffffff).autoClear(true);
  
  canvas = (HCanvas) H.add(new HCanvas(P3D));  

  font1 = createFont("Arial", 48);
  
  HText f1 = new HText("some regular text",48, font1);
  f1.fill(#98FCFF).anchorAt(H.CENTER).loc(width/2,height/2);
  f1.noStroke();
  canvas.add(f1);  // change this for H.add to see the difference

  H.drawStage();
  noLoop();
}

void draw() {}```
