### ISSUE TITLE
install instructions not functioning.

### ISSUE THREAD

**Issue by NicTanghe** [hype/HYPE_Processing#167]
Cant even run the examples becouse the import doesn't work

**Comment by hype** [comment]
works fine.

1. https://github.com/hype/HYPE_Processing/tree/lib_staging
2. download .zip / GREEN button
3. unzip download ZIP file
4. go to "distribution" folder
5. unzip HYPE.zip
6. move HYPE folder to processing/libraries folder
7. run any examples

the instructions are listed on the front page : https://github.com/hype/HYPE_Processing under Getting Started
Install to Processing Sketchbook
