### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by amejias101** [hype/HYPE_Processing#79]
Someone please correct me if I'm wrong but I think there used to be a way to import sound into the AS3 version of HYPE. If this is the case, will it be added to the processing port?

**Comment by admin96** [comment]
Use minim or the current native processing sound library. Both of these can easily be used with HYPE. Is there any specific reason you want to see the audio features implemented in the library and are you looking for some specific functionality to be implemented?

**Comment by amejias101** [comment]
nothing especificaly, I was just wondering if it would be possible and included into the framework. Thinking specifically with the web.

**Comment by admin96** [comment]
https://github.com/micknoise/Maxim
