### ISSUE TITLE
HCallBack() is not class anymore

### ISSUE THREAD

**Issue by bablukid** [hype/HYPE_Processing#82]
Hey,
Sorry for the newbie question :
All the examples on the website for HDrawablePool are using
```
new HCallback(){
public void run(Object obj) {
//...
}
}

```
wich is not possible in java AFAIK since HCallback() is an interface and not a class.

For exemple, the code demoed here
http://www.hypeframework.org/examples/HDrawablePool/example_001/index.html
outputs this  in sublime text 
> build.pde:14:0:14:0: Cannot find a class or type named âHCallBackâ
> [Finished in 2.6s with exit code 1]

**Comment by tracerstar** [comment]
Hi bablukid,

Can you check your source code? That demo is in the repo and runs fine from Sublime Text.

Your error message is interesting, as the error you are getting is for HCallBack and not HCallback (note the capital B in your error message). Can you check the case of that line in your code and try again and see if you still get the problem. If changing cases fixes it, I'm going to mark this as closed and not an issue.

Thanks,
Ben.

**Comment by bablukid** [comment]
Arrgh you're right, it was just a typo.
Sorry I'm unfamiliar with Processing and misunderstood the error message...
Thanks a lot for help !

**Comment by tracerstar** [comment]
No problem, glad to be able to help.
