### ISSUE TITLE
loadPixels lead a nullPointerException in Processing 3

### ISSUE THREAD

**Issue by pdcxs** [hype/HYPE_Processing#95]
In the method updateBuffer() of class HCanvas, when _graphics.loadPixels() is runing, program throws a nullpointer exception in processing 3. But if put the next _graphics.beginDraw() in the previous of _graphics.loadPixels(), this problem will be fixed.

**Comment by hype** [comment]
yes weve fixed this... check the library branch. well merge to master soon

On Tuesday, November 10, 2015, Eric Brown <notifications@github.com> wrote:

> In the method updateBuffer() of class HCanvas, when _graphics.loadPixels()
> is runing, program throws a nullpointer exception in processing 3. But if
> put the next _graphics.beginDraw() in the previous of
> _graphics.loadPixels(), this problem will be fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hype/HYPE_Processing/issues/95>.
>


-- 

Joshua Davis

234 Jefferson Ave. Mineola, New York 11501
m. +1.516.417.3111
e. studio@joshuadavis.com

portfolio : http://www.joshuadavis.com
twitter   : http://twitter.com/joshuadavis
facebook  : http://www.facebook.com/JoshuaDavisStudios
instagram : http://instagram.com/praystation

**Comment by hype** [comment]
https://github.com/hype/HYPE_Processing/tree/library here.
